{
  "154.9.26.72": {
    "status": "timeout",
    "timestamp": 1750727593.945673,
    "details": {
      "ip": "154.9.26.72",
      "stages": [
        {
          "name": "\u521d\u59cbPING",
          "attempts": 1,
          "result": "timeout"
        },
        {
          "name": "PING\u91cd\u8bd5(3\u6b21)",
          "attempts": 3,
          "result": "timeout"
        },
        {
          "name": "API\u9a8c\u8bc1",
          "attempts": 4,
          "api1": {
            "status": "failed",
            "api": "API1",
            "attempt": 1,
            "reason": "HTTPSConnectionPool(host='api.oioweb.cn', port=443): Max retries exceeded with url: /api/http/ping?url=154.9.26.72&t=1750727602 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fac7d368430>: Failed to resolve 'api.oioweb.cn' ([Errno -2] Name or service not known)\"))"
          },
          "api2": {
            "status": "failed",
            "api": "API2",
            "attempt": 1,
            "reason": "HTTP 404",
            "response_time": 1709
          }
        }
      ],
      "timestamp": 1750727593.945673
    }
  },
  "46.3.112.16": {
    "status": "timeout",
    "timestamp": 1750727605.6881459,
    "details": {
      "ip": "46.3.112.16",
      "stages": [
        {
          "name": "\u521d\u59cbPING",
          "attempts": 1,
          "result": "timeout"
        },
        {
          "name": "PING\u91cd\u8bd5(3\u6b21)",
          "attempts": 3,
          "result": "timeout"
        },
        {
          "name": "API\u9a8c\u8bc1",
          "attempts": 4,
          "api1": {
            "status": "failed",
            "api": "API1",
            "attempt": 1,
            "reason": "HTTPSConnectionPool(host='api.oioweb.cn', port=443): Max retries exceeded with url: /api/http/ping?url=46.3.112.16&t=1750727613 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fac7d35c700>: Failed to resolve 'api.oioweb.cn' ([Errno -2] Name or service not known)\"))"
          },
          "api2": {
            "status": "failed",
            "api": "API2",
            "attempt": 1,
            "reason": "HTTP 404",
            "response_time": 3742
          }
        }
      ],
      "timestamp": 1750727605.6881459
    }
  }
}