{
  "154.29.148.16": {
    "status": "timeout",
    "timestamp": 1751677818.6967297,
    "details": {
      "ip": "154.29.148.16",
      "stages": [
        {
          "name": "\u521d\u59cbPING",
          "attempts": 1,
          "result": "timeout"
        },
        {
          "name": "PING\u91cd\u8bd5(3\u6b21)",
          "attempts": 3,
          "result": "timeout"
        },
        {
          "name": "API\u9a8c\u8bc1",
          "attempts": 4,
          "api1": {
            "status": "failed",
            "api": "API1",
            "attempt": 1,
            "reason": "HTTPSConnectionPool(host='api.oioweb.cn', port=443): Max retries exceeded with url: /api/http/ping?url=154.29.148.16&t=1751677826 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f7bf69632e0>: Failed to resolve 'api.oioweb.cn' ([Errno -2] Name or service not known)\"))"
          },
          "api2": {
            "status": "failed",
            "api": "API2",
            "attempt": 1,
            "reason": "HTTP 404",
            "response_time": 2235
          }
        }
      ],
      "timestamp": 1751677818.6967297
    }
  }
}